name: "External Action"
description: "This is the action that is called by wg-process workflow"
inputs:
  some-input:
    description: "An input for the custom action"
    required: true
runs:
  using: "composite"  # Define this as a composite action
  steps:
    - name: Run a Simple Command
      run: |
        echo "Running external action from wg-tools"
        echo "Received inputs: ${{ inputs.input1 }}, ${{ inputs.input2 }}"
      shell: bash
    - name: Call custom action in Repo 3
      uses: wg-test/actions/.github/workflows@main
      with:
        input3: "value3"
        input4: "value4"
