name: "External Action"
description: "This is the action that is called by wg-process workflow"
inputs:
  input1:
    description: "An example input"
    required: true
  input2:
    description: "Another example input"
    required: false
  ref-name:
    description: "The branch or tag reference"
    required: true
runs:
  using: "composite"  # Define this as a composite action
  steps:
    - name: Run a Simple Command
      run: |
        echo "Running external action from wg-tools"
        echo "Received inputs: ${{ inputs.input1 }}, ${{ inputs.input2 }}"
        echo "Ref name is: ${{ inputs.ref-name }}"
      shell: bash
    - name: Call custom action in Repo 3
      uses: wg-test/actions/.github/action@$main
      with:
        input3: "value3"
        input4: "value4"
