# actions-repo-2/custom-action-1/action.yml
name: Custom Action 1 in Repo 2

description: This action calls a custom action in Repo 3

inputs:
  some-input:
    description: "An input for the custom action"
    required: true

runs:
  using: "composite"
  steps:
    - name: Call custom action in Repo 3
      uses: wg-test/actions/.github/workflows@main
      with:
        another-input: ${{ inputs.some-input }}
