name: Example Workflow
on: 
  push:
    branches: main

on:
  workflow_dispatch:  # Enables manual trigger

env:
  GLOBAL_VAR: "Hello World"actions

jobs:
  example-job:
    runs-on: ubuntu-latest
    steps:
      - name: Print Global Variable
        run: echo "The global variable is $GLOBAL_VAR"dsfsdf.ylm
