name: Example Workflow

on: 
  push:
    branches: 
      - main
  workflow_dispatch:  # Enables manual trigger


jobs:
  example-job:
    runs-on: ubuntu-latest
    steps:
      - name: Print Global Variable
      

        run: 
          GLOBAL_VAR = "Hello World"
          echo "The global variable is $GLOBAL_VAR"
